version: "3.7"

services:
  api:
    build: .
    ports:
      - 80:80
      - 443:443
    restart: always

  mongodb:
    image: mongo:latest
    volumes:
      - "mongodb_volume:/data/db"
    ports:
      - 27017:27017
    restart: always

volumes:
  mongodb_volume: